### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by RivathaX** [ryanocf/sampcac-loader#1]
Hey,

dein Script für die UDF funktioniert super, aber ich wollte gerne den sampcac-loader etwas abändern.
Leider kriege ich die beiden Libs bzw. Addons wie Boost und BlackBone nicht in das Projekt integriert.

Könntest du mir bitte da weiterhelfen? Sonst top arbeit und vor allem sehr verständlich.

Viele Grüße

**Comment by RivathaX** [comment]
Und ist da eine Möglichkeit bei der SAMP UDF so um die 10-20 Mapmarker in verschiedenen Farben zu erstellen? 
Würde mich sehr über eine Antwort freuen.

Was ich eigentlich modifizieren wollte ist das kein cmd mehr angeht und das Tool von dir nur im Hintergrund die Adresse ausliest und wiedergibt.

Viele Grüße

**Comment by ryanocf** [comment]
Hey,

> dein Script für die UDF funktioniert super, aber ich wollte gerne den sampcac-loader etwas abändern.
Leider kriege ich die beiden Libs bzw. Addons wie Boost und BlackBone nicht in das Projekt integriert.

Boost & Blackbone kannst du in der README.md in den Credits finden.
Diese haust du irgendwo hin und fixed den include path:
(Kann sein das du Blackbone selbst compilen musst. idk)

![](https://img.ryano.cc/T2Uo4KHV08cz.png)
![](https://img.ryano.cc/UkqgZeuy0LVd.png)

Für Blackbone musst du nur die bestimmten Ordner neu angeben und für Boost solltest du es am besten zu deinen Systemvariablen hinzufügen (PATH) und mit dem global `$(BOOST)` includen.


> Was ich eigentlich modifizieren wollte ist das kein cmd mehr angeht und das Tool von dir nur im Hintergrund die Adresse ausliest und wiedergibt.

Dafür löscht oder am besten kommentierst du die console und alle outputs (app: `std::cout`, dll: `console->log`) aus.

Mit dieser Information solltest du hinkriegen, was du erreichen möchtest.
Für alles Weitere kann ich dich leider nur auf https://www.learncpp.com/ weiterleiten 😎
